# Use a node.js base image compatible with both ARM and x86
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Create data files with random text content
RUN mkdir -p /tmp/data \
    && for i in $(seq 1 30); do dd if=/dev/urandom of=/tmp/data/$i.txt bs=1M count=100; done

# Expose port 8080
EXPOSE 8080

# Command to run the application
CMD ["node", "Server.js"]
